### ISSUE TITLE
UID for user app

### ISSUE THREAD

**Issue by tdgroot** [ByteInternet/hypernode-docker#21]
It'd be nice if the UID for user app would be `1000`, because (in most cases) that would align with the host user. Currently the UID for app is `1001` and the user of `1000` is `mailhog`.

So for example when I have a mount to a Hypernode docker, my username `timon` would align with the guest user `app`. This would solve a lot of file permission problems.

**Comment by vdloo** [comment]
Hi @tdgroot wasn't that already fixed earlier? https://github.com/ByteInternet/hypernode-docker/issues/15

**Comment by vdloo** [comment]
```
vdloo@workstation4:~/code/projects/hypernode-docker$ docker pull docker.hypernode.com/byteinternet/hypernode-docker:latest
vdloo@workstation4:~/code/projects/hypernode-docker$ docker run docker.hypernode.com/byteinternet/hypernode-docker:latest

root@c1b65546b0a4 ~ # id app
uid=1000(app) gid=1000(app) groups=1000(app),4(adm),999(mysql),119(varnish)
root@c1b65546b0a4 ~ # id mailhog
uid=1001(mailhog) gid=1001(mailhog) groups=1001(mailhog)
```

**Comment by tdgroot** [comment]
You're right. We were working with an older layer :(.

Thanks for clarifying!
