### ISSUE TITLE
Update magerun2

### ISSUE THREAD

**Issue by peterjaap** [ByteInternet/hypernode-docker#27]
```
app@589d1cccff9d:~$ magerun2 --version
n98-magerun2 version 3.0.4 by netz98 GmbH
```

On production Hypernode;

```
$ magerun2 --version
n98-magerun2 version 3.0.7 by netz98 GmbH
```

3.0.7 has fixes for errors in 2.3.1 and 2.2.8.

**Comment by vdloo** [comment]
should be in the latest image now:
```
app@cf234353489c:~$ magerun2 --version
n98-magerun2 version 3.0.8 by netz98 GmbH
```
we try to build a new image for every hypernode release that we do so if it ends up on your production hypernode (without placing a newer version there yourself) it should also always eventually end up in the image. If you're in a hurry you can also always `/usr/local/bin/magerun self-update` to update the version in your docker environment directly.

**Comment by peterjaap** [comment]
Awesome, thanks!

Yeah we roll our own image based on yours, so I already added the update command there to always get the latest version but I thought I'd mention it here anyways.
