### ISSUE TITLE
UID for App User

### ISSUE THREAD

**Issue by BrentRobert** [ByteInternet/hypernode-docker#28]
Is it possible the app user switched to ID 1000 again? If I use 1001 following the docs I get the mailhog user.

**Comment by vdloo** [comment]
Hi @BrentRobert, I just pulled the latest image (release-6328 @ 2019-04-24 15:59:43 UTC) and the id/gid of the app user is still 1000:
```
root@5008ea06a051 ~ # id -u app
1000
root@5008ea06a051 ~ # id -g app
1000
```
are you still experiencing problems with the latest version?

**Comment by BrentRobert** [comment]
That's right, and the docs say it should be 1001, so it switched?

**Comment by vdloo** [comment]
Oh good catch, the docs should also say 1000 so that's incorrect. Previously the uid/gid was wrongly 1001. We switched that back to 1000 to fix that discrepancy, see https://github.com/ByteInternet/hypernode-docker/issues/15

**Comment by vdloo** [comment]
@BrentRobert I made a PR to change this in the docs, https://github.com/ByteInternet/hypernode-docker/pull/31 can you verify that this fixes the problem?

**Comment by BrentRobert** [comment]
Looks good to me!
