### ISSUE TITLE
Dev Environment

### ISSUE THREAD

**Issue by BrentRobert** [ByteInternet/hypernode-docker#29]
Hi,

How should we use this as a development environment if the database get's dropped when we stop the container. Dumping the database and importing it again every iteration seems like quite a hassle?

**Comment by kerrermanisNL** [comment]
Hi Brent, have you considered setting up a database docker? That will allow you to kill the Hypernode docker whilst keeping the database up.

**Comment by BrentRobert** [comment]
That's one option, but as the hypernode-vagrant solution has been deprecated I guessed the experience would be the same using hypernode-docker.

Maybe an example to set this up should be added to the magento 2 example documentation?

**Comment by markvds** [comment]
I think it's good to dive a little into Docker and its configuration using _docker-compose_. You can easily mount `/var/lib/mysql` to a local path. You'll do the same with `/data/web/magento2` so your project's code and data persists.

For development, we chose to add a separate Percona Docker container (and mount its `/var/lib/mysql` of course). That way we can access the data of any project, even if the project's Hypernode container is not running. Also, we can make backups (dumps) of all data at once without having to start any Hypernode container.
