### ISSUE TITLE
Keys have changed?

### ISSUE THREAD

**Issue by markvds** [ByteInternet/hypernode-docker#35]
I noticed yesterday that the public keys in `/root/.ssh/authorized_keys` seem to have changed. I don't know exactly in which release, but as we try to keep up with releases, I think it has changed in 6740. 

It doesn't match https://github.com/ByteInternet/hypernode-docker/blob/master/keys/insecure_key.pub anymore.

**Comment by vdloo** [comment]
Oops, accidentally closed this. Good catch Mark! This will be fixed in a release later today

**Comment by markvds** [comment]
I did not say thank you and did not close the issue. Thank you! And I'll close the issue now :)
