### ISSUE TITLE
Mails are not delivered to Mailhog anymore

### ISSUE THREAD

**Issue by markvds** [ByteInternet/hypernode-docker#38]
I don't know exactly for how long because I blamed myself for a while, but Mailhog doesn't catch mails anymore.

I dived into it and found that there are some TLS/SASL configuration directives in Postfix' `main.cf` that force Postfix using authentication and encryption while talking to Mailhog. Mailhog doesn't understand a word Postfix says.

If you remove all directives about TLS/SASL from `/etc/postfix/main.cf`, Mailhog catches mails again the way it should.

**Comment by SanderRoosingh** [comment]
Hi @markvds, thank you for telling us! We applied a solution and this should soon be shipped with the new hypernode-docker.

**Comment by markvds** [comment]
I just checked and Mailhog works like a charm again! Thanks!
