### ISSUE TITLE
could not load host key: /etc/ssh/ssh_host_dsa_key

### ISSUE THREAD

**Issue by SolsWebdesign** [ByteInternet/hypernode-docker#42]
Hello, I'm trying the new docker.hypernode.com/byteinternet/hypernode-buster-docker-php73-mysql57 to start local development with magento2.4 but am running into the following issue: the docker container will run and then hang after the following lines:

*** Runit started as PID 287
/etc/ssh/sshd_config line 6: Deprecated option UsePrivilegeSeparation
/etc/ssh/sshd_config line 7: Deprecated option KeyRegenerationInterval
/etc/ssh/sshd_config line 8: Deprecated option ServerKeyBits
/etc/ssh/sshd_config line 16: Deprecated option RSAAuthentication
/etc/ssh/sshd_config line 19: Deprecated option RhostsRSAAuthentication
Could not load host key: /etc/ssh/ssh_host_dsa_key

not sure what I'm missing. I'm on windows the the (older) docker.hypernode.com/byteinternet/hypernode-docker works fine.

anybody any ideas?

**Comment by SolsWebdesign** [comment]
Okay found my way in using command winpty docker exec -i -t my_magento24 bash and did a bash /etc/my_init.d/60_restart_services.sh and finally got it all working :-) closing this issue

**Comment by FryingDutch** [comment]
Currently on Linux Debian, new to hypernode. Having the exact same issue, anybody got an idea how to solve this issue?
