### ISSUE TITLE
ElasticSearch support

### ISSUE THREAD

**Issue by nocturnalfrog** [ByteInternet/hypernode-docker#43]
Add ElasticSearch support to the docker image cfr. the live hypernode nodes.

Or if this is too hard to realise; document a workflow where ElasticSearch runs as a different service.

**Comment by peterjaap** [comment]
Elasticsearch has been added; https://changelog.hypernode.com/changelog/release-7836-elasticsearch-support-in-all-hypernode-docker-images/

@vdloo are the Elastic extensions `analysis-phonetic` and `analysis-icu` (needed for Magento 2.4) also available?

**Comment by peterjaap** [comment]
@vdloo it looks like the containers aren't updated yet, I'm still getting `a94c77d88785` for `docker.hypernode.com/byteinternet/hypernode-buster-docker-php74-mysql57:latest`.

**Comment by peterjaap** [comment]
Extensions confirmed;

```
root@a337d8b3500a /usr/share/elasticsearch # bin/elasticsearch-plugin list
analysis-icu
analysis-phonetic
```
