### ISSUE TITLE
Mailhog not working?

### ISSUE THREAD

**Issue by Aquive** [ByteInternet/hypernode-docker#53]
See screenshot. Somehow the webinterface of Mailhog is not working/loading as it should. The browser console has also erros.

```
Error: [$interpolate:noconcat] Error while interpolating: {{preview.previewHTML}}<style id="stylish-14" class="stylish" type="text/css">#jr_overlay {
 display: none;   
}</style>
Strict Contextual Escaping disallows interpolations that concatenate multiple expressions when a trusted value is required
```
And every time I click any button:

`Uncaught SyntaxError: Identifier 'API_PUBLIC_KEY' has already been declared
`

Is this an issue with the image or a local problem? Any ideas how to fix this?

![MailHog](https://user-images.githubusercontent.com/197229/132351934-20aacfaf-d782-4b88-aad1-6c33bbe550fd.png)

**Comment by vdloo** [comment]
Hi @Aquive,

I can't reproduce this. I do see a similar broken markup when the page is still loading though:

![hog_000](https://user-images.githubusercontent.com/1437341/141134373-1bf20a8a-4dc0-489a-83e3-b0018c6c7ef1.png)

And then when it's finished loading it's fine:

![hog2](https://user-images.githubusercontent.com/1437341/141134370-5f48d354-5ebc-40c2-8ef9-8d5383a88406.png)

Are you sure your client is blocking anything and breaking things? Have you tried incognito and with browser extensions disabled?

**Comment by Aquive** [comment]
I will look into the suggestions you did the next time I'll need mailhog. Thanks.
