### ISSUE TITLE
Phpmyadmin deprecation notices

### ISSUE THREAD

**Issue by jdereus87** [ByteInternet/hypernode-docker#66]
When using the latest image (hypernode-buster-docker-php81-mysql80:latest) I noticed phpmyadmin gets a few deprecation errors. The current version is 4.9.5. Newest version on moment of writing is 5.1.3. My guess is an update would fix the deprecation errors

**Comment by Aquive** [comment]
I have the same issue.

**Comment by tdgroot** [comment]
This problem has been resolved in the latest Hypernode Docker image versions!
