### ISSUE TITLE
Magerun2 needs updating in php8.1 image

### ISSUE THREAD

**Issue by dheesbeen** [ByteInternet/hypernode-docker#69]
In the 8.1 image magerun2 command is not working because the version is not compatible with php 8.X

**Comment by tdgroot** [comment]
Have you tried using `n98-magerun2-5.0.0`?

**Comment by dheesbeen** [comment]
@tdgroot Yes tried, and works. A manual upgrade works. But would be nice if the correct version was in the docker images by default. If we could create a pull request for this we would :-)

**Comment by DjQuinnEXP** [comment]
@tdgroot Is it possible that you can set the /usr/local/bin/magerun2 alias for 8.1 symlinked to the /usr/local/bin/n98-magerun2-5.0.0

Thanks

**Comment by dheesbeen** [comment]
ln -sf /usr/local/bin/n98-magerun2-5.0.0 /usr/local/bin/magerun2
ln -sf /usr/local/bin/n98-magerun2-5.0.0 /usr/local/bin/magerun

**Comment by tdgroot** [comment]
We now install the `latest` version of n98-magerun2 on the Docker images.
