### ISSUE TITLE
nginx config is not reloaded

### ISSUE THREAD

**Issue by peterjaap** [ByteInternet/hypernode-docker#7]
The nginx config does not seem to reload when I change a file in `~/nginx/`. Sanity check; when I add a file there with a deliberate mistake, on a production Hypernode this is what I'm getting;

```
app@83ezze-clientname-magweb-do:~/nginx$ echo "wutwut" > server.test && cat server.test
wutwut


Your Nginx configuration contains errors, please check
/data/web/nginx/nginx_error_output to see them.

app@83ezze-clientname-magweb-do:~/nginx$ cat nginx_error_output 
nginx: [emerg] unexpected end of file, expecting ";" or "}" in /etc/nginx/app/server.test:2
nginx: configuration file /etc/nginx/nginx.conf test failed


Your Nginx configuration contains errors, please check
/data/web/nginx/nginx_error_output to see them.
```

But when I do this in the Hypernode container, nada;

```
root@hypernode-deployment-66b9d66b54-hz7gj /data/web/nginx # echo "wutwut" > server.test && cat server.test
wutwut
root@hypernode-deployment-66b9d66b54-hz7gj /data/web/nginx # 
```

Also after restarting the nginx service, nothing happens;

```
cat /etc/my_init.d/60_restart_services.sh | grep nginx > restart_nginx.sh && bash restart_nginx.sh && rm restart_nginx.sh
```

**Comment by peterjaap** [comment]
Found a workaround; 

```
cp -R /data/web/nginx/ssl /etc/nginx/app/ssl
cat /etc/my_init.d/60_restart_services.sh | grep nginx > restart_nginx.sh && bash restart_nginx.sh && rm restart_nginx.sh
```

It seems that the files from `~/nginx` aren't read at all.

**Comment by vdloo** [comment]
Perhaps this has something to do with inotify in the docker fs, I'm pretty sure that doesn't work. There's a periodic cron to run `/usr/bin/nginx_config_reloader` manually to work around that, but if you're scripting against the system and expecting the inotify handler to trigger it when something is written to /data/web/nginx like it is on a real hypernode (or a Virtualbox vagrant, the cron is not fast enough. Does it work if you run `/usr/bin/nginx_config_reloader` manually?
