### ISSUE TITLE
hypernode-buster-docker-php81-mysql80 contains different keys to repo

### ISSUE THREAD

**Issue by andy-igoo** [ByteInternet/hypernode-docker#72]
Hi, probably a quick one this.

Public keys in `~/.ssh/authorized_keys` are for a key named `insecure_testing_key` and does not work with the key contained within https://github.com/ByteInternet/hypernode-docker/tree/master/keys

**Comment by AlexanderGrooff** [comment]
Hi @andy-igoo, we've identified the issue you're describing and we'll be fixing this in the upcoming release. Thanks for the bugreport :+1:
