### ISSUE TITLE
Upgrade Varnish 4 to Varnish 6

### ISSUE THREAD

**Issue by peterjaap** [ByteInternet/hypernode-docker#74]
The Varnish version bundled in this Docker container is Varnish 4, which won't work with the Magento core VCL

**Comment by vdloo** [comment]
yup, great idea @peterjaap! https://changelog.hypernode.com/release-8851-varnish-6-for-docker-images-php-7-4-and-up/

**Comment by peterjaap** [comment]
Nice! :raised_hands:
