### ISSUE TITLE
Support php 8.2

### ISSUE THREAD

**Issue by leonhelmus** [ByteInternet/hypernode-docker#78]
Hello Hypernode!

Magento will soon release magento 2.4.6 which requires compatibility with php 8.2.

It would be great if these images will also support php 8.2.

Regards,

Leon

**Comment by tdgroot** [comment]
Hi Leon,

Thank you for reporting!

We have released PHP 8.2 on the platform, but haven't released the Docker version yet. We'll update this as soon as possible, we'll let you know once it's available :).

**Comment by leonhelmus** [comment]
@tdgroot  Awesome! Thanks!

**Comment by tdgroot** [comment]
The PHP 8.2 images are now available!

**Comment by leonhelmus** [comment]
@tdgroot  Nice! I think it would also be a good idea to update the readme. I think your missing it below:
These are the URLs of the containers with specific configurations:
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php56-mysql56:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php70-mysql56:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php71-mysql56:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php72-mysql56:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php73-mysql56:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php74-mysql56:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php80-mysql56:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php81-mysql56:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php56-mysql57:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php70-mysql57:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php71-mysql57:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php72-mysql57:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php73-mysql57:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php74-mysql57:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php80-mysql57:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php81-mysql57:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php56-mysql80:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php70-mysql80:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php71-mysql80:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php72-mysql80:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php73-mysql80:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php74-mysql80:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php80-mysql80:latest
docker pull docker.hypernode.com/byteinternet/hypernode-buster-docker-php81-mysql80:latest

**Comment by tdgroot** [comment]
Spot on! Updated the README :)
