### ISSUE TITLE
Changing domain from hypernode.hypernode.local to custom.hypernode.local

### ISSUE THREAD

**Issue by AngelsDustz** [ByteInternet/hypernode-docker#9]
Hello, is there a way to configure a custom URL? I've been looking around a bit but I can't figure it out.
The hypernode-vagrant uses the folder name, it would be cool if this was a simple config item.

**Comment by vdloo** [comment]
you could do the same as the Vagrant does and set up a hostname to point to the Docker ip in the `/etc/hosts` on your host:

```
172.17.0.2 myshop.hypernode.local
```

And then set the Magento [baseurl](https://support.hypernode.com/knowledgebase/change-baseurl-magento2/#Configuring_your_base_URL8217s_using_SSH) to http://myshop.hypernode.local for example. Then you should be able to access the shop hosted from the Docker on that (custom) URL.

**Comment by vdloo** [comment]
that's possible, you can do that in Docker by manually managing the network or by using docker-compose or something to do it for you, see https://stackoverflow.com/a/35359185/4158804. but with dockers you might not really want to do that and use something dynamic like service discovery instead, it really depends on what your use-case is. if I had to set something up from scratch I'd probably use something like HashiCorp Consul to [manage DNS](https://www.consul.io/docs/agent/dns.html) by placing service checks on each Docker and then using something like [dnsmasq](https://www.morethanseven.net/2014/04/25/consul/) to expose the service domains to the host.

**Comment by AngelsDustz** [comment]
Alright thank you!
